# Generated by Django 2.1.7 on 2019-03-21 08:41

import autoslug.fields
from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thum_image',
            field=models.ImageField(blank=True, upload_to='post/posts/', verbose_name='Thumb image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', slugify=post.models.custom_slugify, unique_for_date='published'),
        ),
    ]
