# Generated by Django 2.1.7 on 2019-03-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20190318_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(default='media/blog/profile.jpg', upload_to='post/profile/', verbose_name='Personal Image'),
        ),
    ]
