# Generated by Django 2.1.7 on 2019-03-19 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0007_auto_20190318_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, verbose_name='First Name')),
                ('second_name', models.CharField(blank=True, max_length=20, verbose_name='First Name')),
                ('image', models.ImageField(default='media/blog/profile.jpg', upload_to='post/profile/', verbose_name='Personal Image')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='image',
        ),
        migrations.RemoveField(
            model_name='author',
            name='second_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.AddField(
            model_name='author',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.Profile'),
            preserve_default=False,
        ),
    ]
